spring:
  application:
    name: cnb-springboot

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: ${PORT:8080}

app:
  message: Hello Spring Boot! 18:32
  title: Spring Boot with Cloud-native Buildpacks
